# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.box = "centos7.0x64"
	config.vm.box_url = "https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.1.0/centos-7.0-x86_64.box"

  if defined? VagrantPlugins::HostManager
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  end

  config.ssh.forward_agent = true

	config.vm.define :bookmanager do |web|
		web.vm.hostname = 'book.manager.aucfan.com'
		web.vm.network :private_network, ip: "192.168.33.100"
		config.vm.synced_folder "../../", "/deploy/book-manager/", :create => true, :owner=> 'vagrant', :group=> 'vagrant', :mount_options=>['dmode=777,fmode=777']
		web.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", 1024]
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
		end
	end

	config.vm.provision :chef_solo do |chef|
		chef.add_recipe "base"
	end
end
